name: Keep Render Alive

on:
  schedule:
    - cron: "*/15 * * * *" # Runs every 15 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Site
        run: curl -s https://rahul-portfolio-lmo7.onrender.com> /dev/null
